#!/bin/bash

###Nutrition Department - Titan Upload
###Script to upload student data to TitanK12
###

###Get Titan Cognos Report from DOE SFTP
###NOTE: 7/7/2021 - need to change to RedClay instance when have correct access
sshpass -f '/home/philmore/.ssh/DOE' sftp -oHostKeyAlgorithms=+ssh-dss colonialdata@ftp.doe.k12.de.us <<EOF
get Cognos/Titan-en.csv
exit
EOF

###Create data file
echo "Student Identifier, First Name, Middle Name, Suffix, State Identifier, Email, Date of Birth, Gender, Race, Ethnicity, Allergies, Tags, Academic Year, School (Site), Grade, Homeroom, Household ID, Home Address (Street), City, State, Zip, Mailing Address (Street), Mailing City, Mailing State, Mailing Zip, Head of Household First Name, Head of Household Middle Name, Head of Household Last Name, Head of Household Cell Phone, Head of Household Home Phone, Head of Household Work Phone, Head of Household Email, Head of Household Relationship" > redclay-titan.csv

awk -F',' 'NR>1{print $6","$7","$8","$9","$10","$6","$12","$13","$15","$16","$4","$1","$2","$11","$18","$32","$19","$21","$22","$23","$24","$26","$27","$28","$30","$31","$32","$37","$35","$36","$34","$39}' Titan-en.csv > redclay-titan.csv


###Upload Data
